config/routes.rb
Rails.application.routes.draw do
  resources :cats

  match '/curl_example' => 'request_example#get_example', via: :get
  # TEST: curl -H "Content-Type: application/json" -X POST -d "{\"cs\":[{\"name\":\"TEST\",\"description\":\"DESC\",\"age\":99}]}" http://localhost:3000/curl_example
  match '/curl_example' => 'request_example#notifyUpdate', via: :post

  match "/register"           => 'request_example#register', via: :post
  match "/system/:id/notify"  => 'request_example#updateSystem', via: :post
  match "/task/:id/notify"    => 'request_example#updateTask', via: :post

  #Versioning test
  #examples: localhost:3000/v1/test
  #          localhost:3000/v2/test
  scope module: 'api' do
      namespace :v1 do
        match "test" => "api#test", via: :all
      end

      namespace :v2 do
        match "test" => "api#test", via: :all
      end
  end

end

app/models/cat.rb
class Cat < ActiveRecord::Base
end

app/controllers/api/v1/api_controller.rb
module Api::V1
  class ApiController < ApplicationController

    def test
      render text: 'API V1 test'
    end

  end
end

app/controllers/api/v2/api_controller.rb
module Api::V2
  class ApiController < ApplicationController

    def test
      render text: 'API V2 test'
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name, :description, :age)
    end
end

app/controllers/request_example_controller.rb
class RequestExampleController < ApplicationController
  protect_from_forgery with: :null_session

  def get_example
    render text: 'Thanks for sending a GET request!'
  end

  def notifyUpdate

    if JSON.parse( request.body.read )
      json = JSON.parse request.body.read
      json["cats"].each do |cat|
        newCat = Cat.new
        newCat.name = cat["name"]
        newCat.description = cat["description"]
        newCat.age = cat["age"]
        newCat.save()
      end
      render text: "OK"
    else
      render text: "ERROR"
    end

  end

  def register
    render text: "register"
  end

  def updateSystem
    render text: "updateSystem called on system with ID #{params[:id]}"
  end

  def updateTask
    render text: "updateTask called on task with ID #{params[:id]}"
  end

end

app/helpers/api/v1/api_helper.rb
module Api::V1::ApiHelper
end

app/helpers/api/v2/api_helper.rb
module Api::V2::ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/request_example_helper.rb
module RequestExampleHelper
end

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.name %></td>
        <td><%= cat.description %></td>
        <td><%= cat.age %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cat.description %>
</p>

<p>
  <strong>Age:</strong>
  <%= @cat.age %>
</p>

<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apitest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>